[book]
authors = ["haixuanTao"]
language = "en"
multilingual = false
src = "src"
title = "Haixuan Xavier Tao"
description = "Inspired by Rustdoc resume, I wanted to use a Rust tool to build an enhanced resume. Mdbook seemed like a great fit, and what is a resume other than a documentation of self."
[rust]
edition = "2018"

[output.html.playground]
editable = true

[output.html]
additional-css = ["custom.css"]
google-analytics = "UA-134601956-5"