[book]
authors = ["haixuanTao"]
language = "en"
multilingual = false
src = "src"
title = "Haixuan Xavier Tao"
[rust]
edition = "2018"


[output.html.playground]
editable = true

[output.html]
additional-css = ["custom.css"]
additional-js = ["instagram-embed.js"]
no-section-label = true
